export const PI = Math.PI;
export const ABS = (value: number) => Math.abs(value);
export const FLOOR = (value: number) => Math.floor(value);
export const RADIANS = (degree: number) => (degree * PI) / 180;
export const DEGREES = (radian: number) => (radian * 180) / PI;
export const SIN = (radian: number) => Math.sin(radian);
export const COS = (radian: number) => Math.cos(radian);
export const TAN = (radian: number) => Math.tan(radian);
export const ASIN = (radian: number) => Math.asin(radian);
export const ACOS = (radian: number) => Math.acos(radian);
export const ATAN = (radian: number) => Math.atan(radian);
export const ATAN2 = (radian1: number, radian2: number) => Math.atan2(radian1, radian2);
